version: '3.9'

services:
  web:
    build: .
    ports:
      - "80:5000"   # host:container
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=Birahe;User Id=sa;Password=@6eGM92c5nec:p9.;Encrypt=False;TrustServerCertificate=True;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "@6eGM92c5nec:p9."
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
